# Generated by Django 6.0.3 on 2026-05-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Dairy', max_length=255)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('system_sender_email', models.EmailField(help_text='Email used to send automated notifications', max_length=254)),
                ('system_password', models.CharField(help_text='App-specific password for the sender email', max_length=255)),
                ('support_email', models.EmailField(help_text='Customer-facing support email', max_length=254)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('tiktok_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company Configuration',
                'verbose_name_plural': 'Company Configuration',
            },
        ),
    ]
