# Generated by Django 6.0 on 2026-10-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_companyconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("occasional", "Occasional"),
                    ("visitor", "Visitor"),
                ],
                default="visitor",
                max_length=20,
            ),
        ),
    ]
