# Generated by Django 6.0.3 on 2026-05-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
                ('admin_note', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('resolved', 'Resolved')], default='new', max_length=10)),
            ],
        ),
    ]
