# Generated by Django 6.0.3 on 2026-05-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_order_by_remove_order_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending'),
        ),
    ]
