# Generated by Django 6.0.3 on 2026-05-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
