# Generated by Django 6.0 on 2026-06-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture_src',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
