# Generated by Django 6.0 on 2026-06-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_picture_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture_src',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
