# Generated by Django 6.0.3 on 2026-04-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('feedback', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_topic', models.CharField(choices=[('PRODUCT', 'Product Quality'), ('DELIVERY', 'Delivery Service'), ('PRICE', 'Pricing/Billing'), ('SUGGESTION', 'General Suggestion'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
