# Generated by Django 6.0 on 2026-06-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='full_name',
            new_name='username',
        ),
    ]
